
name: Publish project to Maven repository
# OR, publish per each commit
on:
  push:
    branches: [ master, develop ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew core:build
      - name: Create release
        uses: actions/create-release@v1
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          RELEASE_NAME: "v${GITHUB_SHA}"
          RELEASE_BODY: "Automated release"
          TAG_NAME: ${{ github.ref_name }}
      - name: Upload JAR file to release
        uses: actions/upload-artifact@v2
        with:
          name: oraxen-1.174.0.jar
          path: ./build/libs/oraxen-1.174.0.jar
          retention-days: 30
